"""Adiciona gamificacao ao usuario

Revision ID: 73c72a353974
Revises: a8e00e737015
Create Date: 2025-12-01 20:01:39.407727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c72a353974'
down_revision = 'a8e00e737015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pontos', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nivel', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('nivel')
        batch_op.drop_column('pontos')

    # ### end Alembic commands ###
