"""Adiciona delivery_pin ao Pedido

Revision ID: 83a834eff0a5
Revises: 8b76d2889a6e
Create Date: 2025-12-02 09:42:30.722337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a834eff0a5'
down_revision = '8b76d2889a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_pin', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('delivery_pin')

    # ### end Alembic commands ###
