"""Adiciona imagem_url ao Produto

Revision ID: 8b76d2889a6e
Revises: 73c72a353974
Create Date: 2025-12-01 20:54:09.604302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b76d2889a6e'
down_revision = '73c72a353974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('imagem_url')

    # ### end Alembic commands ###
